### ISSUE TITLE
Add query and mutation controls for the traffic light window buttons

### ISSUE THREAD

**Issue by matthew-carroll** [macosui/macos_window_utils.dart#27]
Every Mac desktop window has three little window control buttons, often called "traffic lights".

These buttons have a default appearance, but their location can be changed by the developer.

The traffic lights create at least a couple of issues for UI developers. 

First, content needs to avoid the traffic lights. If I'm building a custom app bar, or allowing my content to flow to the top of the window, how do I know where those traffic lights are? This requires an ability to query the current size and location of the traffic lights, from the platform.

Second, if I'm building a custom app bar, it's conventional that the traffic light buttons should appear vertically centered in that app bar. Therefore, I'd like to be able to tell the platform where to put the traffic lights.

I recommend approaching this problem as pass-through control of the platform. I don't recommend trying to hide information, or simplify behavior. The platform has an API for these details - making that API available through this package via Dart is the most versatile option available. Simplified behaviors and widgets can be added on top in macos_ui.

**Comment by Adrian-Samoticha** [comment]
> First, content needs to avoid the traffic lights. If I'm building a custom app bar, or allowing my content to flow to the top of the window, how do I know where those traffic lights are? This requires an ability to query the current size and location of the traffic lights, from the platform.

macos_window_utils provides the [`TitlebarSafeArea`](https://pub.dev/documentation/macos_window_utils/latest/widgets_titlebar_safe_area/TitlebarSafeArea-class.html) class for this very purpose.

When the full-size content view is enabled, it uses [`WindowManipulator.getTitlebarHeight`](https://pub.dev/documentation/macos_window_utils/latest/window_manipulator/WindowManipulator/getTitlebarHeight.html) to retrieve the height of the title bar and accordingly adds padding to its child.

---

While there is currently no way to freely position the traffic light buttons, you can manipulate their position by changing the window’s [toolbar style](https://pub.dev/documentation/macos_window_utils/latest/macos_ns_window_toolbar_style/NSWindowToolbarStyle.html). (So, when building your own custom app bar, be sure to simply choose a toolbar style with the correct size.)

Personally, I am not aware of any API that allows you to change the position of the window buttons freely. It’s possible that applications that do move them either do it by [like this](https://stackoverflow.com/a/52803798/17099858) or simply by hiding the “real” traffic light buttons and implementing their own versions of them. I assume Opera GX, for example, does the latter.

**Comment by matthew-carroll** [comment]
I'm not sure how to use the toolbar style to achieve the goal I mentioned.

I start with:

```dart
WindowManipulator.makeTitlebarTransparent();
WindowManipulator.hideTitle();
WindowManipulator.enableFullSizeContentView();
```
The above configuration is needed so that I can display tabs at the top of the window, instead of showing the window title.

Then, I tried every toolbar style, and none of them cause the traffic lights to move at all.

```dart
WindowManipulator.setToolbarStyle(toolbarStyle: /** I tried every value here **/);
```

**Comment by Adrian-Samoticha** [comment]
Be sure to call [`WindowManipulator.addToolbar`](https://pub.dev/documentation/macos_window_utils/latest/window_manipulator/WindowManipulator/addToolbar.html) before setting the toolbar style.

**Comment by matthew-carroll** [comment]
Ok, using `addToolbar()` before `setToolbarStyle()` allowed me to move the traffic lights. In my case, `unifiedCompact` seemed to be the closest position for what I'm building.

I see now that the docs for `setToolbarStyle()` mention `addToolbar()`. I'm curious why those two don't go together? Would it ever be appropriate to call `setToolbarStyle()` without first adding a toolbar? And when you add a toolbar, is there not an implied style? Could you not pass the style to `addToolbar()`?

I also found the term `addToolbar()` to be confusing, because it sounds as if you can keep adding more and more toolbars. Like adding items to a collection. But calling `addToolbar()` multiple times doesn't seem to have any effect. As far as I can tell, `addToolbar()` really means something like "show toolbar with default style".

**Comment by Adrian-Samoticha** [comment]
I admit that the names aren’t very intuitive, but the reason for this is that I modeled them loosely after the way in which you add to or modify toolbars of an [NSWindow](https://developer.apple.com/documentation/appkit/nswindow) in Swift. In Swift, you’d first create an [NSToolbar](https://developer.apple.com/documentation/appkit/nstoolbar) object, then add it to the window, and then set its style.

I suppose having the toolbar be added or removed automatically based on an argument to `setToolbarStyle` would make the library a little more intuitive to use, but at the same time, if I were to add more customization options to the toolbar, deviating too much from the way things are handled in Swift might make things more difficult in the long run.

**Comment by cbenhagen** [comment]
Adding an `NSToolbar` might have unintended side effects like reacting to double clicks everywhere in your custom toolbar created on the Flutter side. See https://github.com/macosui/macos_ui/issues/308 for a discussion about how to avoid that.

**Comment by Adrian-Samoticha** [comment]
> Adding an `NSToolbar` might have unintended side effects like reacting to double clicks everywhere in your custom toolbar created on the Flutter side. See [macosui/macos_ui#308](https://github.com/macosui/macos_ui/issues/308) for a discussion about how to avoid that.

I’ve been thinking about adding a way to add native buttons to the toolbar to fix that. So far I haven’t really dedicated any time to researching this approach, though.

**Comment by cbenhagen** [comment]
Having native buttons might work for simple apps but as soon as you need custom behaviors or style you are back to wanting full control from the Flutter side. The approach outlined in the linked issue is the only way to achieve this I have found so far.

**Comment by Adrian-Samoticha** [comment]
> Having native buttons might work for simple apps but as soon as you need custom behaviors or style you are back to wanting full control from the Flutter side. The approach outlined in the linked issue is the only way to achieve this I have found so far.

True. I’ll look into your code and see if it can be integrated well into macos_window_utils when I have time to do so.

**Comment by Adrian-Samoticha** [comment]
I’ve experimented a little and found that there is indeed a way to move those buttons, however, you cannot move them outside of the title bar area:

<img width="280" alt="image" src="https://github.com/macosui/macos_window_utils.dart/assets/86920182/33958355-f1d5-4d2b-ac6a-6cd3108b5602">

You can, though, increase the title bar area by adding a toolbar:

<img width="265" alt="image" src="https://github.com/macosui/macos_window_utils.dart/assets/86920182/b3b18340-7d49-4a6d-8f68-658125ea0566">

**Comment by Adrian-Samoticha** [comment]
Alright, [version 1.3.0](https://pub.dev/packages/macos_window_utils/versions/1.3.0) resolves this.
