### ISSUE TITLE
Make it possible to center the window on the screen

### ISSUE THREAD

**Issue by matthew-carroll** [macosui/macos_window_utils.dart#37]
Is there currently a set of APIs that makes it possible to set the size of the window and place it at the center of the screen?

If not, it would be great to have those APIs. I'm trying to control the initial launch of the app to center a window of a particular window size.

**Comment by Adrian-Samoticha** [comment]
There currently is not, but implementing such functionality shouldn’t be too difficult.

**Comment by Adrian-Samoticha** [comment]
Apparently, [`NSWindow`](https://developer.apple.com/documentation/appkit/nswindow) has a [`center`](https://developer.apple.com/documentation/appkit/nswindow/1419090-center) method which does exactly that, however, I’d argue that it’d be best to go all the way and offer methods to modify the window’s [`frame`](https://developer.apple.com/documentation/appkit/nswindow/1419697-frame), thus allowing the window to be placed at arbitrary positions.

**Comment by Adrian-Samoticha** [comment]
Excuse the delay. This feature is now impelemted.
